import { AnimatePresence, m } from "framer-motion";
import { AlertTriangle, Percent, Plus, Sparkles, Trash2, X } from "lucide-react";
import type { MouseEvent as ReactMouseEvent } from "react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { Currency } from "@/components/shared/Currency";
import { cn } from "@/lib/utils";
import type { SalEconomicRules, SalLineView, SalVoiceDraft } from "../types";

function getMgLinkedTotal(line: SalLineView): number {
  return line.linkedCharges
    .filter((charge) => charge.code.startsWith("MG."))
    .reduce((sum, charge) => sum + charge.total, 0);
}

function getManualSurchargeTotal(line: SalLineView): number {
  return line.linkedCharges
    .filter((charge) => !charge.code.startsWith("MG."))
    .reduce((sum, charge) => sum + charge.total, 0);
}

function getMgAllocationState(
  economicRules: SalEconomicRules,
  mgLineId: string,
): "active" | "inactive" {
  const manualAlloc = economicRules.mgManualAllocations?.[mgLineId];
  if (manualAlloc && manualAlloc.length > 0) return "active";
  return "inactive";
}

function isMgTariffCode(code: string): boolean {
  return code.includes(".MG.");
}

function formatPct(value: number): string {
  return `${value.toLocaleString("it-IT")}%`;
}

type MaggiorazioniHeaderClusterProps = {
  economicRules: SalEconomicRules;
  lines: SalLineView[];
  manualSurchargeLines: SalLineView[];
  mgLines: SalLineView[];
  suggestedMgVoices: SalVoiceDraft[];
  tariffMgSignals: SalLineView[];
  onAddMgVoice: (voice: SalVoiceDraft) => void;
  onOpenAllocation: (mgLineId: string) => void;
  onOpenMgContextMenu?: (mgLineId: string, event: ReactMouseEvent) => void;
  onRemove: (mgLineId: string) => void;
};

/**
 * Completely rethought Maggiorazioni UI:
 * - Zero dedicated vertical panel.
 * - Lives as a compact, elegant cluster inside the table header.
 * - Active MG shown as tiny professional pills (click to allocate, hover X to remove).
 * - Suggestions live in a transient, beautifully designed dropdown (never eat permanent space).
 * - Pending tariff signals shown as a single subtle warning badge.
 */
export function MaggiorazioniHeaderCluster({
  economicRules,
  lines,
  manualSurchargeLines,
  mgLines,
  suggestedMgVoices,
  tariffMgSignals,
  onAddMgVoice,
  onOpenAllocation,
  onOpenMgContextMenu,
  onRemove,
}: MaggiorazioniHeaderClusterProps) {
  const [showSuggestions, setShowSuggestions] = useState(false);
  const addButtonRef = useRef<HTMLButtonElement>(null);

  const totalMg = lines.reduce((sum, line) => sum + getMgLinkedTotal(line), 0);
  const manualTotal = manualSurchargeLines.reduce(
    (sum, line) => sum + getManualSurchargeTotal(line),
    0,
  );
  const pendingSignals = tariffMgSignals.filter(
    (line) => getMgLinkedTotal(line) <= 0 && line.surchargePercent <= 0,
  );

  const tariffMgLines = useMemo(
    () => mgLines.filter((l) => isMgTariffCode(l.voice.code)),
    [mgLines],
  );
  const otherPctLines = useMemo(
    () => mgLines.filter((l) => !isMgTariffCode(l.voice.code)),
    [mgLines],
  );

  const allMg = useMemo(() => [...tariffMgLines, ...otherPctLines], [tariffMgLines, otherPctLines]);

  const hasAnyMg = allMg.length > 0;
  const hasSignals = pendingSignals.length > 0;
  const hasSuggestions = suggestedMgVoices.length > 0;

  const totalSurcharge = totalMg + manualTotal;

  // Live allocation info derived strictly from the latest economicRules + target lines.
  // We compute the *actual maggiorazione total* (€ generated by this MG), not the base of the selected voices.
  // This makes "Disattiva" immediately correct and shows the real surcharge amount on each pill.
  const getLiveInfo = useCallback(
    (mgLineId: string, mgPercent: number) => {
      const alloc = economicRules.mgManualAllocations?.[mgLineId] ?? [];
      if (alloc.length === 0) {
        return { isActive: false as const, voiceCount: 0, mgTotal: 0 };
      }
      const allocSet = new Set(alloc);
      let base = 0;
      for (const line of lines) {
        if (allocSet.has(line.id)) base += line.grossAmount;
      }
      const mgTotal = base * (mgPercent / 100);
      return { isActive: true as const, voiceCount: alloc.length, mgTotal };
    },
    [economicRules, lines],
  );

  if (!hasAnyMg && !hasSignals && !hasSuggestions) {
    return null;
  }

  return (
    <div className="flex min-w-0 flex-wrap items-center gap-1.5 text-10px">
      {/* MG Pills cluster */}
      {hasAnyMg ? (
        <div className="flex min-w-0 flex-wrap items-center gap-0.5">
          {allMg.map((mgLine) => {
            const live = getLiveInfo(mgLine.id, mgLine.voice.unitPrice);
            return (
              <MgMiniPill
                economicRules={economicRules}
                key={mgLine.id}
                mgLine={mgLine}
                liveIsActive={live.isActive}
                liveMgTotal={live.mgTotal}
                liveVoiceCount={live.voiceCount}
                onOpenAllocation={onOpenAllocation}
                onOpenContextMenu={
                  onOpenMgContextMenu
                    ? (event: ReactMouseEvent) => onOpenMgContextMenu(mgLine.id, event)
                    : undefined
                }
                onRemove={onRemove}
              />
            );
          })}
        </div>
      ) : null}

      {/* Total */}
      {hasAnyMg ? (
        <span className="ml-0.5 shrink-0 font-mono font-bold tabular-nums text-[var(--info-base)]">
          +<Currency value={totalSurcharge} />
        </span>
      ) : null}

      {/* Pending signals badge — aligned to new taller h-8 pills */}
      {hasSignals ? (
        <button
          className="inline-flex h-8 items-center gap-0.5 rounded-md border border-[var(--warning-base)]/40 bg-[var(--warning-soft)]/70 px-1.5 text-10px font-semibold text-[var(--warning-base)] transition-colors hover:bg-[var(--warning-soft)]"
          onClick={() => {
            /* future: could open a dedicated "review signals" flow */
          }}
          title={`${pendingSignals.length} voci tariffarie con maggiorazione non ancora applicata`}
          type="button"
        >
          <AlertTriangle className="size-3.5" />
          <span className="tabular-nums">{pendingSignals.length}</span>
        </button>
      ) : null}

      {/* Add / Suggestions trigger — enhanced signaling */}
      <button
        ref={addButtonRef}
        className={cn(
          "group/mgbtn inline-flex h-8 items-center gap-1 rounded-md border px-1.5 text-10px font-semibold transition-all active:scale-[0.985]",
          showSuggestions
            ? "border-[var(--accent-primary)] bg-[var(--accent-primary)] text-[var(--text-inverse)]"
            : hasSuggestions
              ? "border-[var(--accent-primary)]/40 bg-[var(--accent-primary)]/[0.08] text-[var(--accent-primary)] hover:bg-[var(--accent-primary)]/[0.14]"
              : "border-[var(--border-subtle)]/60 bg-[var(--surface-base)] text-[var(--text-secondary)] hover:border-[var(--accent-primary)]/40 hover:bg-[var(--accent-primary)]/[0.06] hover:text-[var(--accent-primary)]",
        )}
        onClick={() => setShowSuggestions((s) => !s)}
        title={
          hasSuggestions
            ? `${suggestedMgVoices.length} maggiorazioni suggerite — clicca per scegliere`
            : "Aggiungi maggiorazione"
        }
        type="button"
      >
        {hasSuggestions ? (
          <Sparkles className="size-3.5 text-[var(--accent-primary)] group-hover/mgbtn:text-[var(--text-inverse)]" />
        ) : (
          <Plus className="size-3.5" />
        )}
        <span className="font-bold tracking-tight">MG</span>

        {/* Suggestion count badge — excellent compact signal */}
        {hasSuggestions ? (
          <span className="ml-0.5 rounded-full bg-white/90 px-1 text-9px font-black tabular-nums text-[var(--accent-primary)] ring-1 ring-[var(--accent-primary)]/30">
            {suggestedMgVoices.length}
          </span>
        ) : null}
      </button>

      {/* Floating suggestions dropdown */}
      <MgSuggestionsDropdown
        anchorRef={addButtonRef}
        isOpen={showSuggestions}
        onClose={() => setShowSuggestions(false)}
        suggestions={suggestedMgVoices}
        onAdd={onAddMgVoice}
      />
    </div>
  );
}

/* ---------- Mini pill for an active MG (header style) — larger, clearer distinction, whole-pill target ---------- */

function MgMiniPill({
  economicRules,
  liveIsActive,
  liveMgTotal,
  liveVoiceCount,
  mgLine,
  onOpenAllocation,
  onOpenContextMenu,
  onRemove,
}: {
  economicRules: SalEconomicRules;
  liveIsActive?: boolean;
  liveMgTotal?: number;
  liveVoiceCount?: number;
  mgLine: SalLineView;
  onOpenAllocation: (mgLineId: string) => void;
  onOpenContextMenu?: ((event: ReactMouseEvent) => void) | undefined;
  onRemove: (mgLineId: string) => void;
}) {
  // Prefer live values (computed from the freshest economicRules + target lines)
  // so that "Disattiva" immediately flips the pill to inactive state.
  const allocState = getMgAllocationState(economicRules, mgLine.id);
  const isActive = liveIsActive ?? allocState === "active";
  const targetCount = liveVoiceCount ?? economicRules.mgManualAllocations?.[mgLine.id]?.length ?? 0;
  // liveMgTotal (when present) is the *actual surcharge amount* this MG generates on the assigned voices.
  // Fallback to the pre-computed linkedCharges total (also the real maggiorazione €).
  const total =
    liveMgTotal ?? mgLine.linkedCharges.find((entry) => entry.code.startsWith("MG."))?.total ?? 0;

  const isRealMg = isMgTariffCode(mgLine.voice.code);
  const isOs = mgLine.voice.code.startsWith("OS.");

  // Distinct visual language:
  // - Real MG (the true .MG. system): strong accent blue tones
  // - "Normalized" % voices (OS. or other standard items treated as MG rows): softer amber/warning tones + tiny type tag
  const tone = isRealMg ? "real" : "other";

  const handleOpen = (e: ReactMouseEvent) => {
    // Whole pill (except the remove button) opens the allocation modal
    e.stopPropagation();
    onOpenAllocation(mgLine.id);
  };

  const handleRemove = (e: ReactMouseEvent) => {
    e.stopPropagation();
    onRemove(mgLine.id);
  };

  return (
    <button
      className={cn(
        "group/pill inline-flex h-8 shrink-0 cursor-pointer select-none items-center overflow-hidden rounded-md border p-0 text-10px transition-all active:scale-[0.985]",
        tone === "real"
          ? isActive
            ? "border-[var(--accent-primary)]/30 bg-[color-mix(in_srgb,var(--accent-primary)_6%,var(--surface-base))]"
            : "border-[var(--border-subtle)]/50 bg-[var(--surface-base)]"
          : isActive
            ? "border-[var(--warning-base)]/30 bg-[color-mix(in_srgb,var(--warning-base)_6%,var(--surface-base))]"
            : "border-[var(--border-subtle)]/45 bg-[var(--bg-muted)]/50",
      )}
      onClick={handleOpen}
      onContextMenu={onOpenContextMenu}
      title={mgLine.voice.description}
      type="button"
    >
      {/* Percentage — color tells the kind immediately */}
      <span
        className={cn(
          "flex h-full items-center px-2.5 font-mono font-extrabold tabular-nums",
          tone === "real"
            ? "bg-[var(--info-soft)] text-[var(--info-base)]"
            : "bg-[var(--warning-soft)] text-[var(--warning-base)]",
        )}
      >
        {formatPct(mgLine.voice.unitPrice)}
      </span>

      {/* Code + optional type tag for non-real MG */}
      <span
        className={cn(
          "flex max-w-[128px] items-center gap-0.5 truncate border-l px-2.5 font-mono font-semibold tracking-tight",
          tone === "real"
            ? isActive
              ? "border-[var(--accent-primary)]/15 text-[var(--text-primary)]"
              : "border-[var(--border-subtle)]/30 text-[var(--text-secondary)]"
            : "border-[var(--warning-base)]/15 text-[var(--text-primary)]",
        )}
      >
        {mgLine.voice.code}
        {!isRealMg && (
          <span className="ml-0.5 rounded bg-[var(--warning-soft)] px-0.5 py-px text-8px font-black uppercase tracking-wider text-[var(--warning-base)] ring-1 ring-[var(--warning-base)]/20">
            {isOs ? "OS" : "%"}
          </span>
        )}
      </span>

      {/* Allocation / status indicator — voices and € clearly separated */}
      {isActive ? (
        <>
          {/* Voices count — distinct soft success badge */}
          <span className="flex items-center border-l border-[var(--border-subtle)]/30 pl-2 pr-1.5">
            <span className="rounded bg-[var(--success-soft)] px-1.5 py-px font-mono text-9px font-extrabold tabular-nums text-[var(--success-base)] ring-1 ring-[var(--success-base)]/20">
              {targetCount}v
            </span>
          </span>

          {/* € total generated by this MG — stronger visual weight, separate segment */}
          {total > 0 ? (
            <span className="flex items-center border-l border-[var(--border-subtle)]/30 bg-[var(--accent-primary)]/[0.06] px-2 font-mono text-10px font-extrabold tabular-nums text-[var(--accent-primary)]">
              <Currency value={total} />
            </span>
          ) : null}
        </>
      ) : (
        <span className="flex items-center border-l border-[var(--border-subtle)]/30 px-1.5 text-[var(--warning-base)]">
          <AlertTriangle className="size-3.5" />
        </span>
      )}

      {/* Remove — dedicated, always-visible but discreet zone on the far right.
          Clicking anywhere else on the pill opens the modal. */}
      <button
        aria-label={`Rimuovi ${mgLine.voice.code}`}
        className={cn(
          "flex h-full items-center border-l px-1.5 text-[var(--text-tertiary)] transition-all",
          "opacity-30 hover:bg-[var(--danger-soft)] hover:text-[var(--danger-base)] hover:opacity-100",
          "group-hover/pill:opacity-70",
        )}
        onClick={handleRemove}
        title="Rimuovi maggiorazione"
        type="button"
      >
        <Trash2 className="size-3.5" />
      </button>
    </button>
  );
}

/* ---------- Beautiful suggestions dropdown (zero permanent space) ---------- */

function MgSuggestionsDropdown({
  anchorRef,
  isOpen,
  onClose,
  onAdd,
  suggestions,
}: {
  anchorRef: React.RefObject<HTMLButtonElement | null>;
  isOpen: boolean;
  onClose: () => void;
  onAdd: (voice: SalVoiceDraft) => void;
  suggestions: SalVoiceDraft[];
}) {
  const [rect, setRect] = useState<DOMRect | null>(null);

  // Recompute position when opening or on resize
  const updatePosition = useCallback(() => {
    if (anchorRef.current) {
      setRect(anchorRef.current.getBoundingClientRect());
    }
  }, [anchorRef]);

  // Close on outside click / escape
  useEffect(() => {
    if (!isOpen) return;

    updatePosition();

    const handleClickOutside = (event: MouseEvent) => {
      const target = event.target as Node;
      if (anchorRef.current && !anchorRef.current.contains(target)) {
        // Also ignore clicks inside the portal menu (we'll give it a data attr)
        const menu = document.querySelector("[data-mg-suggestions-menu]");
        if (!menu?.contains(target)) {
          onClose();
        }
      }
    };

    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === "Escape") onClose();
    };

    const handleResize = () => updatePosition();

    document.addEventListener("mousedown", handleClickOutside);
    document.addEventListener("keydown", handleEscape);
    window.addEventListener("resize", handleResize);

    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
      document.removeEventListener("keydown", handleEscape);
      window.removeEventListener("resize", handleResize);
    };
  }, [isOpen, onClose, anchorRef, updatePosition]);

  if (!isOpen || suggestions.length === 0) return null;

  const menuWidth = 320;
  const left = rect ? Math.min(rect.left, window.innerWidth - menuWidth - 16) : 0;
  const top = rect ? rect.bottom + 6 : 0;

  return createPortal(
    <AnimatePresence>
      <m.div
        animate={{ opacity: 1, y: 0, scale: 1 }}
        className="fixed z-[200] overflow-hidden rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-base)] shadow-[0_12px_32px_-8px_color-mix(in_srgb,var(--text-primary)_18%,transparent),0_2px_8px_-2px_color-mix(in_srgb,var(--text-primary)_8%,transparent)]"
        data-mg-suggestions-menu
        exit={{ opacity: 0, y: 4, scale: 0.985 }}
        initial={{ opacity: 0, y: 6, scale: 0.985 }}
        style={{
          left: `${left}px`,
          top: `${top}px`,
          width: `${menuWidth}px`,
        }}
        transition={{ duration: 0.12, ease: [0.22, 1.0, 0.36, 1] }}
      >
        <div className="flex items-center justify-between border-b border-[var(--border-subtle)]/60 px-3 py-2">
          <div className="flex items-center gap-1.5 text-11px font-bold text-[var(--text-secondary)]">
            <Percent className="size-3.5 text-[var(--accent-primary)]" />
            Maggiorazioni suggerite
          </div>
          <button
            className="flex size-6 items-center justify-center rounded text-[var(--text-tertiary)] hover:bg-[var(--bg-muted)] hover:text-[var(--text-primary)]"
            onClick={onClose}
            type="button"
          >
            <X className="size-3.5" />
          </button>
        </div>

        <div className="max-h-[260px] overflow-y-auto py-0.5">
          {suggestions.map((voice) => (
            <button
              className="group flex w-full items-center gap-3 border-b border-[var(--border-subtle)]/40 px-3 py-2 text-left last:border-b-0 hover:bg-[var(--accent-primary)]/[0.035]"
              key={voice.id}
              onClick={() => {
                onAdd(voice);
                onClose();
              }}
              type="button"
            >
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2">
                  <span className="font-mono text-12px font-bold text-[var(--text-primary)]">
                    {voice.code}
                  </span>
                  <span className="rounded bg-[var(--info-soft)] px-1 py-px font-mono text-10px font-bold text-[var(--info-base)]">
                    {formatPct(voice.unitPrice)}
                  </span>
                </div>
                <div className="mt-0.5 truncate text-10px text-[var(--text-tertiary)]">
                  {voice.description}
                </div>
              </div>
              <div className="shrink-0 rounded-lg border border-[var(--accent-primary)]/30 bg-[var(--accent-primary)]/[0.06] p-1 text-[var(--accent-primary)] transition-colors group-hover:bg-[var(--accent-primary)] group-hover:text-[var(--text-inverse)]">
                <Plus className="size-3.5" />
              </div>
            </button>
          ))}
        </div>

        <div className="border-t border-[var(--border-subtle)]/60 bg-[var(--bg-muted)]/40 px-3 py-1.5 text-9px text-[var(--text-tertiary)]">
          Clicca per aggiungere la voce MG al SAL
        </div>
      </m.div>
    </AnimatePresence>,
    document.body,
  );
}
